// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoFARZ5HOalhru7v1-qkoyiikuLpcGYXU',
    appId: '1:76250795816:web:f57db71810f553cefe4a1d',
    messagingSenderId: '76250795816',
    projectId: 'fruit-hub-a00b3',
    authDomain: 'fruit-hub-a00b3.firebaseapp.com',
    storageBucket: 'fruit-hub-a00b3.firebasestorage.app',
    measurementId: 'G-KTZEF9PP5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT3f7qJEyMZuvSMP3cyK6l8-oSMJD6R4w',
    appId: '1:76250795816:android:f85b951c88657a41fe4a1d',
    messagingSenderId: '76250795816',
    projectId: 'fruit-hub-a00b3',
    storageBucket: 'fruit-hub-a00b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgxaCjEmpPSeTkFKU_QPvVHXJV00HVHYA',
    appId: '1:76250795816:ios:c105ed7dd6065229fe4a1d',
    messagingSenderId: '76250795816',
    projectId: 'fruit-hub-a00b3',
    storageBucket: 'fruit-hub-a00b3.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgxaCjEmpPSeTkFKU_QPvVHXJV00HVHYA',
    appId: '1:76250795816:ios:c105ed7dd6065229fe4a1d',
    messagingSenderId: '76250795816',
    projectId: 'fruit-hub-a00b3',
    storageBucket: 'fruit-hub-a00b3.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoFARZ5HOalhru7v1-qkoyiikuLpcGYXU',
    appId: '1:76250795816:web:ab1833955932f433fe4a1d',
    messagingSenderId: '76250795816',
    projectId: 'fruit-hub-a00b3',
    authDomain: 'fruit-hub-a00b3.firebaseapp.com',
    storageBucket: 'fruit-hub-a00b3.firebasestorage.app',
    measurementId: 'G-79FE5RKWE2',
  );
}
